### ISSUE TITLE
Should the merge document suffix always be '.xml' ?

### ISSUE THREAD

**Issue by xbonnamy-marklogic** [marklogic-community/smart-mastering-core#217] opened 2018-10-23 09:45 UTC
When a new "merged" document is created it gets an URI with a '.xml' suffix wether the document is a XML or a JSON document.
In example, when 2 JSON documents are merged the resulting document is getting an URI of the following form:
'/com.marklogic.smart-mastering/merged/b9af0298-c171-42e4-8193-1593082761c3.xml' 

In this case, the .xml suffix may be misleading.

**Comment by dmcassel** [comment] 2018-10-23 10:59
Duplicate of #188.

**Closed by dmcassel** 2018-10-23 10:59 UTC
Labels: bug, duplicate
